name: Qt Android Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Android SDK and NDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: '26.1.10909125'
        sdk-version: '19.0'

    - name: Set up Qt 6.9
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.9.0'
        host: linux
        target: android
        arch: armv7
        mirror: 'https://download.qt.io'

    - name: Add Qt to PATH
      run: |
        echo "$QT_ROOT_DIR/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_NDK_ROOT" >> $GITHUB_PATH

    - name: Configure environment variables
      run: |
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
        echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        echo "QT_ROOT=$QT_ROOT_DIR" >> $GITHUB_ENV

    - name: Create build directory
      run: mkdir build && cd build

    - name: Configure with CMake
      working-directory: ./build
      run: |
        cmake .. \
          -DCMAKE_SYSTEM_NAME=Android \
          -DCMAKE_SYSTEM_VERSION=19 \
          -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a \
          -DCMAKE_ANDROID_NDK=$ANDROID_NDK_ROOT \
          -DCMAKE_ANDROID_STL_TYPE=c++_shared \
          -DQT_HOST_PATH=$QT_ROOT_DIR \
          -DCMAKE_PREFIX_PATH=$QT_ROOT_DIR/lib/cmake \
          -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ./build
      run: cmake --build . --parallel

    - name: Package APK
      working-directory: ./build
      run: |
        cmake --build . --target install
        # 或者使用 androiddeployqt 如果需要
        $QT_ROOT_DIR/bin/androiddeployqt \
          --input android-libMyApp.so-deployment-settings.json \
          --output android-build \
          --gradle