name: CMake Build Qt Project

on:
  push:
    branches: [ master ]
    #tags: 
      #- "v*"
  #pull_request:
    #branches: [ master ]

env:
  # Qt 版本
  QT_VERSION: "6.9.0"
  #ANDROID_NDK_VERSION: '26.1.10909125'  # Android NDK 版本
  #ANDROID_SDK_VERSION: '19.0'       # Android SDK 版本
  ANDROID_API: 23
  ANDROID_NDK_VERSION: 26.1.10909125
  ANDROID_ABI: armeabi-v7a
  ANDROID_BUILD_TOOLS_VERSION: "34.0.0"
  ANDROID_SDK_PACKAGES: "platforms;android-33,build-tools;34.0.0,cmdline-tools;latest,platform-tools,ndk;$ANDROID_NDK_VERSION"

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write  # 关键权限
    steps:
    - uses: actions/checkout@v4

    - name: Set up NSIS
      shell: powershell
      run: choco install nsis -y --no-progress

    - name: Verify NSIS
      run: makensis /VERSION

    - name: Compile test script
      run: |
        makensis -V4 test_variables.nsi
        ls

    - name: Run test
      run: |
        # 静默运行测试程序
        .\NSISVariablesDebug.exe /S
        # 等待日志文件生成
        Start-Sleep -Seconds 2
        # 输出日志内容
        Get-Content "$env:TEMP\NSIS_Variables_Debug.log"
        # 检查文件是否存在
        Test-Path "$env:TEMP\NSIS_Variables_Debug.log"

    - name: Complete run
      run: |
        exit 1

    - name: Set up Qt
      id: setup-qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ env.QT_VERSION }}
        host: windows
        target: desktop
      
    - name: Configure and build
      run: |
        mkdir build/windows
        cd build/windows
        cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release ../..
        cmake --build . --config Release

    - name: Verify files and Deploy Qt dependencies
      shell: powershell
      run: |
        #ls
        $QT_BIN = "$env:QT_PATH/bin"
        & "windeployqt.exe" `
          --release `
          --no-compiler-runtime `
          --dir installer `
          "build/windows/Release/calculator.exe"
        Copy-Item "build/windows/Release/calculator.exe" installer
        #ls installer
          # 验证文件存在
          if (-not (Test-Path "installer/calculator.exe")) {
          Write-Error "calculator.exe not found in installer directory!"
          Get-ChildItem -Path installer -Recurse
          exit 1
        }

    - name: Generate NSIS script
      #shell: powershell
      run: |
        @"
          !include "MUI2.nsh"
          Name "calculator"
          OutFile "claculatorInstaller.exe"
          #Unicode true
          InstallDir "$PROGRAMFILES/calculator"
          RequestExecutionLevel admin

          # 安装页面设置
          Page directory
          Page instfiles
          # 卸载页面设置
          UninstPage uninstConfirm
          UninstPage instfiles

          #!define SMPROGRAMS "$SMPROGRAMS"

          !insertmacro MUI_PAGE_DIRECTORY
          !insertmacro MUI_PAGE_INSTFILES
          !insertmacro MUI_LANGUAGE "English"

          Section
            !echo "EEEEEEEEEEEECHO:$INSTDIR"
            SetOutPath /$INSTDIR
            File /r "*"
            # 创建卸载程序
            #WriteUninstaller "/$INSTDIR/Uninstall.exe"
            # 创建开始菜单快捷方式
            #CreateDirectory "/$SMPROGRAMS/calculator"
            #CreateShortCut "$SMPROGRAMS/calculator/calculator.lnk" "$INSTDIR/calculator.exe"
            #CreateShortCut "$SMPROGRAMS/calculator/Uninstall.lnk" "$INSTDIR/Uninstall.exe"
          SectionEnd

          Section "Uninstall"
            # 删除安装的文件
            #Delete "/$INSTDIR/calculator.exe"
            #Delete "/$INSTDIR/Uninstall.exe"
    
            # 删除开始菜单快捷方式
            #Delete "$SMPROGRAMS/calculator/calculator.lnk"
            #Delete "$SMPROGRAMS/calculator/Uninstall.lnk"
            #RMDir "/$SMPROGRAMS/calculator"
            # 删除安装目录（如果为空）
            #RMDir "/$INSTDIR"
          SectionEnd
        "@ | Out-File "installer/installer.nsi" -Encoding UTF8


    - name: Find installer
      shell: powershell
      run:  |
        pwd
        #Get-Content installer/installer.nsi
        Test-Path installer/installer.nsi
        #ls installer

    - name: Compile installer
      run: |
        cd installer
        makensis /V4 installer.nsi
        cd ..
        ls installer

    - name: Release
      uses: softprops/action-gh-release@v2.3.2
      with:
        # Note-worthy description of changes in release
        body: # optional
        # Path to load note-worthy description of changes in release from
        body_path: # optional
        # Gives the release a custom name. Defaults to tag name
        name: # optional
        # Gives a tag name. Defaults to github.ref_name
        tag_name: ${{ github.ref_name }}
        # Creates a draft release. Defaults to false
        draft: # optional
        # Identify the release as a prerelease. Defaults to false
        prerelease: # optional
        # Preserver the order of the artifacts when uploading
        preserve_order: # optional
        # Newline-delimited list of path globs for asset files to upload
        #files: build/windows/Release/calculator.exe
        files: D:/a/calculator/calculator/installer/claculatorInstaller.exe
        # Fails if any of the `files` globs match nothing. Defaults to false
        fail_on_unmatched_files: # optional
        # Repository to make releases against, in <owner>/<repo> format
        repository: # optional
        # Authorized secret GitHub Personal Access Token. Defaults to github.token
        #token: # optional, default is $-{{ github.token }}
        # Commitish value that determines where the Git tag is created from. Can be any branch or commit SHA.
        target_commitish: # optional
        # If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. If there is already a discussion linked to the release, this parameter is ignored.
        discussion_category_name: # optional
        # Whether to automatically generate the name and body for this release. If name is specified, the specified name will be used; otherwise, a name will be automatically generated. If body is specified, the body will be pre-pended to the automatically generated notes.
        generate_release_notes: true
        # Append to existing body instead of overwriting it. Default is false.
        append_body: # optional
        # Specifies whether this release should be set as the latest release for the repository. Drafts and prereleases cannot be set as latest. Can be `true`, `false`, or `legacy`. Uses GitHub api default if not provided
        make_latest: true